# Generated by Django 3.1.4 on 2021-01-15 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0018_auto_20210108_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profiles/photos', verbose_name='Изображение')),
                ('liked', models.ManyToManyField(related_name='liked', to='movies.Movie', verbose_name='Понравивщиеся')),
                ('rating', models.ManyToManyField(related_name='rating', to='movies.Rating', verbose_name='Оценки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wath_later', models.ManyToManyField(related_name='watch_later', to='movies.Movie', verbose_name='Фильмы в смотреть позже')),
            ],
            options={
                'verbose_name': 'Профили',
            },
        ),
    ]
