# Generated by Django 3.1.4 on 2021-01-16 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0020_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='profiles/photos/no-image-user.png', null=True, upload_to='profiles/photos', verbose_name='Изображение')),
                ('liked', models.ManyToManyField(null=True, related_name='liked', to='movies.Movie', verbose_name='Понравивщиеся')),
                ('rating', models.ManyToManyField(null=True, related_name='rating', to='movies.Rating', verbose_name='Оценки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wath_later', models.ManyToManyField(null=True, related_name='watch_later', to='movies.Movie', verbose_name='Фильмы в смотреть позже')),
            ],
            options={
                'verbose_name': 'Профили',
            },
        ),
    ]
