# Generated by Django 3.1.4 on 2021-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_delete_profile'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wath_later',
        ),
        migrations.AddField(
            model_name='profile',
            name='watch_later',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch_later', to='movies.Movie', verbose_name='Фильмы в смотреть позже'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='movies.Movie', verbose_name='Понравивщиеся'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='rating', to='movies.Rating', verbose_name='Оценки'),
        ),
    ]
